export const AUTHORIZATION_BUTTON_TEXT = 'Authorize my Github account'
export const BANNER_TEXT = 'Your Github account was successfully authorized'
export const APP_NAME = 'YouCanChallenge'
export const REPOSITORIES = 'Repositories'
export const PRIVATE_BADGE = 'private'
export const SELECT_A_BRANCH = 'Select a branch'
export const COMMITS_TEXT = 'Commits on'
export const COMMIT_DATE_TEXT = 'commited on'
